---
kind: "operation"
client: "rug-cli 0.16.4-SNAPSHOT"
executor:
  name: "atomist-rugs.travis-editors.UpdateTravisMavenBuild"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.3.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "update-maven"
    sha: "e104acb*"

---
kind: "operation"
client: "rug-cli 0.16.4-SNAPSHOT"
executor:
  name: "atomist-rugs.travis-editors.UpdateTravisMavenBuild"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.3.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "update-maven"
    sha: "24b88f7"

---
kind: "operation"
client: "rug-cli 0.22.0"
editor:
  name: "atomist-rugs.rug-editors.ConvertExistingProjectToRugArchiveWithEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.6.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors"
    branch: "master"
    sha: "00b7e7d*"
  parameters:
    - "editor_name": "AddTypeScriptTest"
    - "rug_archive_name": "rug"
    - "rug_archive_group_id": "atomist"

