---
kind: "operation"
client: "rug-cli 0.16.4-SNAPSHOT"
executor:
  name: "atomist-rugs.travis-editors.UpdateTravisMavenBuild"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.3.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "update-maven"
    sha: "e104acb*"

---
kind: "operation"
client: "rug-cli 0.16.4-SNAPSHOT"
executor:
  name: "atomist-rugs.travis-editors.UpdateTravisMavenBuild"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.3.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "update-maven"
    sha: "24b88f7"

---
kind: "operation"
client: "rug-cli 0.22.0"
editor:
  name: "atomist-rugs.rug-editors.ConvertExistingProjectToRugArchiveWithEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.6.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors"
    branch: "master"
    sha: "00b7e7d*"
  parameters:
    - "editor_name": "AddTypeScriptTest"
    - "rug_archive_name": "rug"
    - "rug_archive_group_id": "atomist"

---
kind: "operation"
client: "rug-cli 0.23.0-SNAPSHOT"
executor:
  name: "UpgradeScalaTestAssertions"
  group: "atomist-rugs"
  artifact: "scala-editors"
  version: "0.1.0"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

---
kind: "operation"
client: "rug-cli 0.23.0-SNAPSHOT"
editor:
  name: "atomist.rug.AddTypeScriptTest"
  group: "atomist"
  artifact: "rug"
  version: "0.1.0"
  origin:
    repo: "git@github.com:atomist/rug"
    branch: "jessitron/microgrammar-refactor"
    sha: "eefca25"
  parameters:
    - "class_under_test": "com.atomist.tree.content.text.OverwriteableTextTreeNode"

---
kind: "operation"
client: "rug-cli 0.23.1-SNAPSHOT"
editor:
  name: "jessitron.microlib-TreeNodePrinter.BringIn"
  group: "jessitron"
  artifact: "microlib-TreeNodePrinter"
  version: "0.1.0"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"
  parameters:
    - "package": "com.atomist.rug.tree.utils"

---
kind: "operation"
client: "rug-cli 0.25.0-SNAPSHOT"
editor:
  name: "atomist.rug.AddTypeScriptTest"
  group: "atomist"
  artifact: "rug"
  version: "0.1.0"
  origin:
    repo: "git@github.com:atomist/rug"
    branch: "delete-dsl"
    sha: "b3c71d6*"
  parameters:
    - "class_under_test": "JavaTypeUsageTest"

---
kind: "operation"
client: "rug-cli 0.25.0-SNAPSHOT"
editor:
  name: "atomist.rug.AddTypeScriptTest"
  group: "atomist"
  artifact: "rug"
  version: "0.1.0"
  origin:
    repo: "git@github.com:atomist/rug"
    branch: "delete-dsl"
    sha: "b3c71d6*"
  parameters:
    - "class_under_test": "com.atomist.rug.kind.java.JavaTypeUsageTest"

---
kind: "operation"
client: "rug-cli 0.24.0"
editor:
  name: "AddTypeScript"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.11.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors"
    branch: "master"
    sha: "e9ca710*"

---
kind: "operation"
client: "rug-cli 0.25.0-SNAPSHOT"
editor:
  name: "JavaTypeUsageTestTypeScriptTest"
  group: "atomist"
  artifact: "rug"
  version: "0.1.0"
  origin:
    repo: "git@github.com:atomist/rug"
    branch: "delete-dsl"
    sha: "ab710aa*"

---
kind: "operation"
client: "rug-cli 0.25.0-SNAPSHOT"
editor:
  name: "JavaTypeUsageTestTypeScriptTest"
  group: "atomist"
  artifact: "rug"
  version: "0.1.0"
  origin:
    repo: "git@github.com:atomist/rug"
    branch: "delete-dsl"
    sha: "de6f9eb*"

---
kind: "operation"
client: "rug-cli 0.25.0-SNAPSHOT"
editor:
  name: "JavaTypeUsageTestTypeScriptTest"
  group: "atomist"
  artifact: "rug"
  version: "0.1.0"
  origin:
    repo: "git@github.com:atomist/rug"
    branch: "delete-dsl"
    sha: "dbf7abc"

---
kind: "operation"
client: "rug-cli 0.25.0-SNAPSHOT"
editor:
  name: "atomist-rugs.rug-upgrade.ConvertRugToTypeScript"
  group: "atomist-rugs"
  artifact: "rug-upgrade"
  version: "0.1.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-upgrade"
    branch: "1e67c1d722094538f928b78351a6629b997c18db"
    sha: "1e67c1d"
  parameters:
    - "rug_name": "ClassAnnotated"

---
kind: "operation"
client: "rug-cli 0.25.0-SNAPSHOT"
editor:
  name: "atomist-rugs.rug-upgrade.ConvertRugToTypeScript"
  group: "atomist-rugs"
  artifact: "rug-upgrade"
  version: "0.1.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-upgrade"
    branch: "1e67c1d722094538f928b78351a6629b997c18db"
    sha: "1e67c1d"
  parameters:
    - "rug_name": "ClassExtended"

---
kind: "operation"
client: "rug-cli 0.25.0-SNAPSHOT"
editor:
  name: "atomist-rugs.rug-upgrade.ConvertRugToTypeScript"
  group: "atomist-rugs"
  artifact: "rug-upgrade"
  version: "0.1.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-upgrade"
    branch: "1e67c1d722094538f928b78351a6629b997c18db"
    sha: "1e67c1d"
  parameters:
    - "rug_name": "AbstractClass"

---
kind: "operation"
client: "rug-cli 0.25.0-SNAPSHOT"
editor:
  name: "AddTypeScriptTest"
  group: "atomist"
  artifact: "rug"
  version: "0.1.0"
  origin:
    repo: "git@github.com:atomist/rug"
    branch: "generators-dir"
    sha: "062d814"
  parameters:
    - "class_under_test": "com.atomist.rug.runtime.js.JavaScriptContext"

---
kind: "operation"
client: "rug-cli 0.25.0"
editor:
  name: "AddTypeScriptTest"
  group: "atomist"
  artifact: "rug"
  version: "0.2.0"
  origin:
    repo: "git@github.com:atomist/rug"
    branch: "master"
    sha: "c0d5777*"
  parameters:
    - "class_under_test": "com.atomist.tree.content.text.microgrammar.MatcherMicrogrammarConstruction"

---
kind: "operation"
client: "rug-cli 0.25.0"
editor:
  name: "AddTypeScriptTest"
  group: "atomist"
  artifact: "rug"
  version: "0.2.0"
  origin:
    repo: "git@github.com:atomist/rug"
    branch: "multiple-use-of-submatcher"
    sha: "e4e5a1e"
  parameters:
    - "class_under_test": "com.atomist.tree.content.text.microgrammar.MultipleUseOfSubmatcher"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "AddTypeScriptTest"
  group: "atomist"
  artifact: "rug"
  version: "0.3.0"
  origin:
    repo: "git@github.com:atomist/rug"
    branch: "master"
    sha: "fa808f2*"
  parameters:
    - "class_under_test": "com.atomist.rug.kind.PandaParsing"

