
// Generated by Rug to TypeScript transpiler.
// To take ownership of this file, simply delete the .rug file
    
import {ProjectEditor} from '@atomist/rug/operations/ProjectEditor'
import {Parameter} from '@atomist/rug/operations/RugOperation'
import {PathExpressionEngine} from '@atomist/rug/tree/PathExpression'
import {File, Project} from '@atomist/rug/model/Core'

/**
       BananaToCarrot
*/


class BananaToCarrot implements ProjectEditor {

    name: string = "BananaToCarrot"
    
    description: string = "BananaToCarrot"
    
    
    
    edit(project: Project) {
    
        let eng: PathExpressionEngine = project.context().pathExpressionEngine();
        
        
    
            let p = project
                if (true) {
                        eng.with<File>(p, '//File()', f => {
                            if (true) {
                                f.replace("banana", "carrots")
                            }
                        })
                }
    
    }

}
export let editor_bananaToCarrot = new BananaToCarrot();