/*
    Generated by Atomist on 12 07 2016 
*/
package com.atomist.test1;

import org.springframework.context.annotation.Configuration;

/**
* Spring Java configuration file for Test1.
* Don't even think of using XML.
*/
@Configuration
public class Test1Configuration {

    // Your beans go here ... 
	// Atomist Bot suggests "maybe use an Atomist project editor to add a sample one?"
}
