/*
    Generated by Atomist on 12 07 2016 
*/
package com.atomist.test1;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.context.web.WebAppConfiguration;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = Test1Application.class)
@WebAppConfiguration
public class Test1ApplicationTests {

	@Test
	public void contextLoads() {
	}
}
